# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-08 08:09
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence'), (12, 'Person'), (13, 'Organistion')], null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='file_group_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(location='/home/jason/projects/statdev-ledger/statdev/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
    ]
