# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-08 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20190808_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='extension',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
