# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_record_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence'), (2001, 'Person'), (2002, 'Organistion')], null=True),
        ),
    ]
