# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-15 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190814_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationpending',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_pending_billing_address', to='accounts.OrganisationAddress'),
        ),
        migrations.AlterField(
            model_name='organisationpending',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_pending_postal_address', to='accounts.OrganisationAddress'),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence'), (2001, 'Person'), (2002, 'Organistion'), (2003, 'Application Communication Logs'), (2004, 'Account Communication Logs')], null=True),
        ),
    ]
