# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-15 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cert_public_liability_insurance',
            field=models.ManyToManyField(blank=True, related_name='cert_public_liability_insurace', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cert_survey',
            field=models.ManyToManyField(blank=True, related_name='cert_survey', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='deed',
            field=models.ManyToManyField(blank=True, related_name='deed', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_briefing_note',
            field=models.ManyToManyField(blank=True, related_name='document_briefing_note', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_completion',
            field=models.ManyToManyField(blank=True, related_name='document_completion', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_determination',
            field=models.ManyToManyField(blank=True, related_name='document_determination', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_determination_approved',
            field=models.ManyToManyField(blank=True, related_name='document_determination_approved', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_draft',
            field=models.ManyToManyField(blank=True, related_name='document_draft', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_draft_signed',
            field=models.ManyToManyField(blank=True, related_name='document_draft_signed', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_final',
            field=models.ManyToManyField(blank=True, related_name='document_final', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_final_signed',
            field=models.ManyToManyField(blank=True, related_name='document_final_signed', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_memo',
            field=models.ManyToManyField(blank=True, related_name='document_memo', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_new_draft',
            field=models.ManyToManyField(blank=True, related_name='document_newdraft', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document_new_draft_v3',
            field=models.ManyToManyField(blank=True, related_name='document_newdraftv3', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='location_route_access',
            field=models.ManyToManyField(blank=True, related_name='location_route_access', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='risk_mgmt_plan',
            field=models.ManyToManyField(blank=True, related_name='risk_mgmt_plan', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='river_lease_scan_of_application',
            field=models.ManyToManyField(blank=True, related_name='river_lease_scan_of_application', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='safety_mgmt_procedures',
            field=models.ManyToManyField(blank=True, related_name='safety_mgmt_plan', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='supporting_info_demonstrate_compliance_trust_policies',
            field=models.ManyToManyField(blank=True, related_name='supporting_info_demonstrate_compliance_trust_policies', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='application',
            name='swan_river_trust_board_feedback',
            field=models.ManyToManyField(blank=True, related_name='document_swan_river_board_feedback', to='applications.Record'),
        ),
    ]
