# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-12 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0008_auto_20190830_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
