# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-01-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20191210_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='land_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='landowner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
