# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-26 03:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_approval_document_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_memo_2',
            field=models.ManyToManyField(blank=True, related_name='document_memo_2', to='applications.Record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence'), (2001, 'Person'), (2002, 'Organistion'), (2003, 'Application Communication Logs'), (2004, 'Account Communication Logs'), (2005, 'Approval')], null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(location='/var/web/statdev-ledger/private-media'), upload_to='uploads/%Y/%m/%d'),
        ),
    ]
