# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-26 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_auto_20201126_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='publish_documents_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='publish_draft_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='publish_final_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
