# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-12-08 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_auto_20201126_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='craft_type',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Craft Type'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='craft_documents', to='applications.Record'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='number_of_crafts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of crafts'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.IntegerField(choices=[(1, 'Referred'), (2, 'Responded'), (3, 'Recalled'), (4, 'Expired'), (5, 'Not Sent')], default=5),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='registration',
            field=models.ManyToManyField(blank=True, related_name='vessel_documents', to='applications.Record'),
        ),
    ]
