# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
