# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_condition_condition_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='advise_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='file_group',
            field=models.IntegerField(blank=True, choices=[(1, 'Permit'), (2, 'Licence/permit'), (3, 'Part 5'), (4, 'Emergency works'), (5, 'Part 5 - Amendment Request'), (6, 'Part 5 - Amendment Application'), (7, 'Test - Application'), (8, 'Amend Permit'), (9, 'Amend Licence'), (10, 'Renew Permit'), (11, 'Renew Licence'), (2001, 'Person'), (2002, 'Organistion'), (2003, 'Application Communication Logs'), (2004, 'Account Communication Logs'), (2005, 'Approval'), (2006, 'Compliance'), (2007, 'Approval Communication Logs')], null=True),
        ),
    ]
