# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20210204_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='external_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
