# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-12 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20210208_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='external_documents',
            field=models.ManyToManyField(blank=True, related_name='compliance_external_documents', to='applications.Record'),
        ),
    ]
