# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_auto_20210219_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='old_approval_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
