# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-01-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Communicate'), (2, 'Assign'), (3, 'Refer'), (4, 'Issue'), (5, 'Decline'), (6, 'Publish'), (7, 'Lodge'), (8, 'Next Step'), (9, 'Change'), (10, 'Create'), (11, 'Cancelled')], null=True),
        ),
    ]
