# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-19 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_auto_20200114_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.IntegerField(choices=[(1, 'Current'), (2, 'Expired'), (3, 'Cancelled'), (4, 'Surrendered'), (5, 'Suspended'), (6, 'Reinstate'), (7, 'Pending'), (8, 'Not Supported')]),
        ),
    ]
